name: ${name}
version: ${version}
author: [Maelys, Luca, Thibault]
depend:
  - SpigotApi
main: ${mainClass}
api-version: 1.20
commands:
  tower:
    description: Admin tools to manage the tower
    permission-message: §cYou dont have the permission.
    permission: tower.command.use